export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_PIC = 'SET_USER_PIC';
export const SET_USER_FIRST_NAME = 'SET_USER_FIRST_NAME';
export const SET_USER_LAST_NAME = 'SET_USER_LAST_NAME';
export const SET_USER_BALANCE = 'SET_USER_BAL';
export const SET_USER_KPOINTS = 'SET_USER_KPOINTS';
export const SET_USER_NOTIFICATIONS_READ = 'SET_USER_NOTIFICATIONS_READ';
export const SET_USER_NOTIFICATIONS_LIST = 'SET_USER_NOTIFICATIONS_LIST';
export const PUSH_USER_NOTIFICATIONS_LIST = 'PUSH_USER_NOTIFICATIONS_LIST';
export const SET_USER_HISTORY_LIST = 'SET_USER_HISTORY_LIST';
export const SET_USER_SHOP_NAME = 'SET_USER_SHOP_NAME';
export const PUSH_USER_HISTORY_LIST = 'PUSH_USER_HISTORY_LIST';

